CREATE TABLE tb_books (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          author VARCHAR(255),
                          cover_url VARCHAR(255),
                          created_at TIMESTAMP(6) NOT NULL,
                          genre VARCHAR(255),
                          isbn VARCHAR(255),
                          publisher VARCHAR(255),
                          synopsis VARCHAR(255),
                          title VARCHAR(255),
                          updated_at TIMESTAMP(6),

                          CONSTRAINT pk_tb_books PRIMARY KEY (id)
);


CREATE TABLE tb_users (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          created_at TIMESTAMP(6) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          updated_at TIMESTAMP(6),
                          username VARCHAR(255) NOT NULL,

                          CONSTRAINT pk_tb_users PRIMARY KEY (id),
                          CONSTRAINT uk_tb_users_email UNIQUE (email),
                          CONSTRAINT uk_tb_users_username UNIQUE (username)
);


CREATE TABLE tb_user_books (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               created_at TIMESTAMP(6) NOT NULL,
                               end_date DATE NOT NULL,
                               read_format VARCHAR(255) NOT NULL,
                               read_status VARCHAR(255) NOT NULL,
                               updated_at TIMESTAMP(6),
                               book_id BIGINT NOT NULL,
                               user_id BIGINT NOT NULL,

                               CONSTRAINT pk_tb_user_books PRIMARY KEY (id),

                               CONSTRAINT ck_tb_user_books_read_format
                                   CHECK (read_format IN ('KINDLE', 'PHYSIC', 'PDF', 'AUDIOBOOK')),

                               CONSTRAINT ck_tb_user_books_read_status
                                   CHECK (read_status IN ('READING', 'FINISHED', 'WISHLIST')),

                               CONSTRAINT fk_tb_user_books_book
                                   FOREIGN KEY (book_id)
                                       REFERENCES tb_books (id),

                               CONSTRAINT fk_tb_user_books_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES tb_users (id)
);


CREATE TABLE tb_reviews (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            created_at TIMESTAMP(6) NOT NULL,
                            rating INTEGER,
                            text TEXT,
                            updated_at TIMESTAMP(6),
                            user_book_id BIGINT,

                            CONSTRAINT pk_tb_reviews PRIMARY KEY (id),

                            CONSTRAINT uk_tb_reviews_user_book
                                UNIQUE (user_book_id),

                            CONSTRAINT fk_tb_reviews_user_book
                                FOREIGN KEY (user_book_id)
                                    REFERENCES tb_user_books (id)
);


CREATE TABLE tb_book_images (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                content_type VARCHAR(255) NOT NULL,
                                image_data BYTEA NOT NULL,
                                review_id BIGINT NOT NULL,

                                CONSTRAINT pk_tb_book_images PRIMARY KEY (id),

                                CONSTRAINT fk_tb_book_images_review
                                    FOREIGN KEY (review_id)
                                        REFERENCES tb_reviews (id)
);