ALTER TABLE tb_users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE tb_books
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS source VARCHAR(30) NOT NULL DEFAULT 'MANUAL';

ALTER TABLE tb_user_books
    ADD COLUMN IF NOT EXISTS started_at DATE,
    ADD COLUMN IF NOT EXISTS finished_at DATE;

ALTER TABLE tb_user_books
    ADD CONSTRAINT uk_tb_user_books_user_book UNIQUE (user_id, book_id);

CREATE TABLE IF NOT EXISTS tb_wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    book_id BIGINT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    price NUMERIC(10, 2),
    store_name VARCHAR(255),
    store_url VARCHAR(255),
    notes TEXT,
    CONSTRAINT pk_tb_wishlist_items PRIMARY KEY (id),
    CONSTRAINT fk_tb_wishlist_items_user
        FOREIGN KEY (user_id) REFERENCES tb_users (id),
    CONSTRAINT fk_tb_wishlist_items_book
        FOREIGN KEY (book_id) REFERENCES tb_books (id)
);

CREATE TABLE IF NOT EXISTS tb_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(512) NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uk_tb_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_tb_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES tb_users (id)
);
